# Generated by Django 5.0.7 on 2024-10-11 07:59

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
    ]
